import type { Client } from '@libsql/client';

/**
 * SQL Schema Definitions with `updated_at` timestamps for Conflict Resolution (Last-Write-Wins)
 */
export const TABLE_DEFINITIONS: string[] = [
  `CREATE TABLE IF NOT EXISTS school_info (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    department TEXT NOT NULL,
    address TEXT NOT NULL,
    phone TEXT NOT NULL,
    academic_year TEXT NOT NULL,
    principal_name TEXT NOT NULL,
    medical_staff_name TEXT NOT NULL,
    head_chef_name TEXT NOT NULL,
    inspector_name TEXT,
    receiver_name TEXT,
    sample_keeper_name TEXT,
    sample_disposer_name TEXT,
    default_print_orientation TEXT,
    creator_name TEXT,
    team_leader_nutrition_name TEXT,
    team_leader_education_name TEXT,
    vice_principal_name TEXT,
    accountant_name TEXT,
    meat_supplier_name TEXT,
    meat_supplier_address TEXT,
    meat_deliverer_name TEXT,
    veg_supplier_name TEXT,
    veg_supplier_address TEXT,
    veg_deliverer_name TEXT,
    seafood_supplier_name TEXT,
    seafood_supplier_address TEXT,
    seafood_deliverer_name TEXT,
    dry_producer_name TEXT,
    dry_producer_address TEXT,
    dry_supplier_name TEXT,
    dry_supplier_address TEXT,
    dry_deliverer_name TEXT,
    logo_url TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS step1_inspections (
    id TEXT PRIMARY KEY,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    food_name TEXT NOT NULL,
    category TEXT NOT NULL,
    quantity TEXT NOT NULL,
    sensory_quality TEXT NOT NULL,
    supplier TEXT NOT NULL,
    expiry_or_certificate TEXT NOT NULL,
    deliverer TEXT NOT NULL,
    inspector TEXT NOT NULL,
    result TEXT NOT NULL,
    notes TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS step2_cookings (
    id TEXT PRIMARY KEY,
    date TEXT NOT NULL,
    meal TEXT NOT NULL,
    dish_name TEXT NOT NULL,
    prep_time TEXT NOT NULL,
    cook_time TEXT NOT NULL,
    cooking_temp TEXT NOT NULL,
    hygiene_status TEXT NOT NULL,
    chef TEXT NOT NULL,
    supervisor TEXT NOT NULL,
    result TEXT NOT NULL,
    notes TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS step3_tastings (
    id TEXT PRIMARY KEY,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    meal TEXT NOT NULL,
    dish_name TEXT NOT NULL,
    sensory_evaluation TEXT NOT NULL,
    serving_temp TEXT NOT NULL,
    sample_weight TEXT NOT NULL,
    storage_location TEXT NOT NULL,
    taster TEXT NOT NULL,
    keeper TEXT NOT NULL,
    result TEXT NOT NULL,
    notes TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS menu_items (
    id TEXT PRIMARY KEY,
    week_number INTEGER NOT NULL,
    month TEXT NOT NULL,
    age_group TEXT NOT NULL,
    day_of_week TEXT NOT NULL,
    breakfast TEXT NOT NULL,
    snack_morning TEXT NOT NULL,
    lunch_main TEXT NOT NULL,
    lunch_soup TEXT NOT NULL,
    lunch_staple TEXT NOT NULL,
    lunch_dessert TEXT NOT NULL,
    afternoon_snack TEXT NOT NULL,
    calories_kcal REAL NOT NULL,
    protein_ratio TEXT NOT NULL,
    status TEXT NOT NULL,
    approved_by TEXT NOT NULL,
    notes TEXT,
    recipe_breakdowns_json TEXT,
    estimated_daily_cost REAL,
    macro_distribution_json TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS sample_disposals (
    id TEXT PRIMARY KEY,
    date_sampled TEXT NOT NULL,
    time_sampled TEXT NOT NULL,
    meal TEXT NOT NULL,
    dish_name TEXT NOT NULL,
    sample_weight TEXT,
    container_type TEXT,
    storage_temp TEXT,
    disposal_date TEXT NOT NULL,
    disposal_time TEXT NOT NULL,
    condition_at_disposal TEXT NOT NULL,
    sampler_name TEXT,
    witness_name TEXT,
    status TEXT NOT NULL,
    notes TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS students (
    id TEXT PRIMARY KEY,
    student_code TEXT NOT NULL,
    full_name TEXT NOT NULL,
    dob TEXT NOT NULL,
    gender TEXT NOT NULL,
    class_name TEXT NOT NULL,
    parent_name TEXT NOT NULL,
    parent_phone TEXT NOT NULL,
    address TEXT NOT NULL,
    attendance_status TEXT NOT NULL,
    allergies_or_diet TEXT,
    enrollment_date TEXT NOT NULL,
    notes TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS health_records (
    id TEXT PRIMARY KEY,
    student_id TEXT NOT NULL,
    student_name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    check_date TEXT NOT NULL,
    height_cm REAL NOT NULL,
    weight_kg REAL NOT NULL,
    nutrition_status TEXT NOT NULL,
    vaccination_status TEXT NOT NULL,
    general_health TEXT NOT NULL,
    doctor_or_examiner TEXT NOT NULL,
    notes TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS staff (
    id TEXT PRIMARY KEY,
    staff_code TEXT NOT NULL,
    full_name TEXT NOT NULL,
    gender TEXT,
    role TEXT NOT NULL,
    qualification TEXT NOT NULL,
    assigned_class_or_dept TEXT,
    assigned_duty TEXT,
    phone TEXT NOT NULL,
    email TEXT,
    hygiene_cert_date TEXT,
    food_safety_cert_date TEXT,
    health_check_date TEXT,
    health_check_expiry TEXT,
    contract_status TEXT,
    start_date TEXT,
    status TEXT,
    notes TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS lesson_plans (
    id TEXT PRIMARY KEY,
    title TEXT,
    theme TEXT NOT NULL,
    target_class TEXT,
    age_group TEXT,
    subject TEXT,
    topic TEXT,
    teacher_name TEXT NOT NULL,
    week_number INTEGER NOT NULL,
    month TEXT,
    date_range TEXT,
    development_field TEXT,
    learning_objectives TEXT,
    activities_plan TEXT,
    preparation TEXT,
    approval_status TEXT NOT NULL,
    approver_name TEXT NOT NULL,
    approval_date TEXT,
    file_attachment_name TEXT,
    notes TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS teacher_salaries (
    id TEXT PRIMARY KEY,
    staff_id TEXT,
    staff_name TEXT NOT NULL,
    role TEXT NOT NULL,
    assigned_class TEXT,
    month TEXT NOT NULL,
    base_salary REAL NOT NULL,
    allowance_responsibility REAL NOT NULL,
    allowance_lunch REAL NOT NULL,
    allowance_other REAL NOT NULL,
    bonus REAL NOT NULL,
    insurance_deduction REAL NOT NULL,
    advance_payment REAL NOT NULL,
    other_deductions REAL NOT NULL,
    work_days_standard REAL NOT NULL,
    work_days_actual REAL NOT NULL,
    net_salary REAL NOT NULL,
    payment_status TEXT NOT NULL,
    payment_method TEXT NOT NULL,
    bank_account TEXT,
    bank_name TEXT,
    notes TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS finance_transactions (
    id TEXT PRIMARY KEY,
    date TEXT NOT NULL,
    type TEXT NOT NULL,
    category TEXT NOT NULL,
    amount REAL NOT NULL,
    payer_or_receiver TEXT NOT NULL,
    method TEXT NOT NULL,
    receipt_number TEXT,
    notes TEXT,
    is_automatic_sync INTEGER DEFAULT 0,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS dish_breakdowns (
    dish_id TEXT PRIMARY KEY,
    dish_name TEXT NOT NULL,
    category TEXT NOT NULL,
    target_age TEXT NOT NULL,
    default_portion_calories REAL,
    breakdown_json TEXT NOT NULL,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS dish_library (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    default_meal_slot TEXT NOT NULL,
    suitable_age TEXT,
    nutrition_tags TEXT,
    calories_estimate REAL,
    description TEXT,
    is_favorite INTEGER DEFAULT 0,
    ingredients_json TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS app_settings (
    id TEXT PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value_json TEXT NOT NULL,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY,
    timestamp TEXT NOT NULL,
    display_time TEXT NOT NULL,
    action TEXT NOT NULL,
    action_label TEXT NOT NULL,
    module TEXT NOT NULL,
    module_name TEXT NOT NULL,
    description TEXT NOT NULL,
    can_undo INTEGER DEFAULT 0,
    previous_data_json TEXT,
    target_id TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`,
  `CREATE TABLE IF NOT EXISTS lightning_state (
    id TEXT PRIMARY KEY,
    custom_dishes_json TEXT,
    custom_counts_json TEXT,
    default_settings_json TEXT,
    updated_at INTEGER DEFAULT (strftime('%s', 'now') * 1000)
  )`
];

export async function ensureTablesInitialized(db: Client): Promise<void> {
  const batchStatements = TABLE_DEFINITIONS.map(sql => ({ sql, args: [] }));
  await db.batch(batchStatements, 'write');

  // Thêm migration các cột còn thiếu nếu table cũ đã tồn tại trong local SQLite hoặc Turso
  const migrations = [
    // school_info migrations
    `ALTER TABLE school_info ADD COLUMN inspector_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN receiver_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN sample_keeper_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN sample_disposer_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN default_print_orientation TEXT;`,
    `ALTER TABLE school_info ADD COLUMN creator_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN team_leader_nutrition_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN team_leader_education_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN vice_principal_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN accountant_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN meat_supplier_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN meat_supplier_address TEXT;`,
    `ALTER TABLE school_info ADD COLUMN meat_deliverer_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN veg_supplier_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN veg_supplier_address TEXT;`,
    `ALTER TABLE school_info ADD COLUMN veg_deliverer_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN seafood_supplier_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN seafood_supplier_address TEXT;`,
    `ALTER TABLE school_info ADD COLUMN seafood_deliverer_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN dry_producer_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN dry_producer_address TEXT;`,
    `ALTER TABLE school_info ADD COLUMN dry_supplier_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN dry_supplier_address TEXT;`,
    `ALTER TABLE school_info ADD COLUMN dry_deliverer_name TEXT;`,
    `ALTER TABLE school_info ADD COLUMN logo_url TEXT;`,
    `ALTER TABLE school_info ADD COLUMN updated_at INTEGER DEFAULT 0;`,

    // step1, step2, step3
    `ALTER TABLE step1_inspections ADD COLUMN updated_at INTEGER DEFAULT 0;`,
    `ALTER TABLE step2_cookings ADD COLUMN updated_at INTEGER DEFAULT 0;`,
    `ALTER TABLE step3_tastings ADD COLUMN updated_at INTEGER DEFAULT 0;`,

    // menu_items
    `ALTER TABLE menu_items ADD COLUMN recipe_breakdowns_json TEXT;`,
    `ALTER TABLE menu_items ADD COLUMN estimated_daily_cost REAL;`,
    `ALTER TABLE menu_items ADD COLUMN macro_distribution_json TEXT;`,
    `ALTER TABLE menu_items ADD COLUMN updated_at INTEGER DEFAULT 0;`,

    // sample_disposals
    `ALTER TABLE sample_disposals ADD COLUMN sample_weight TEXT;`,
    `ALTER TABLE sample_disposals ADD COLUMN container_type TEXT;`,
    `ALTER TABLE sample_disposals ADD COLUMN storage_temp TEXT;`,
    `ALTER TABLE sample_disposals ADD COLUMN sampler_name TEXT;`,
    `ALTER TABLE sample_disposals ADD COLUMN witness_name TEXT;`,
    `ALTER TABLE sample_disposals ADD COLUMN updated_at INTEGER DEFAULT 0;`,

    // students & health
    `ALTER TABLE students ADD COLUMN allergies_or_diet TEXT;`,
    `ALTER TABLE students ADD COLUMN notes TEXT;`,
    `ALTER TABLE students ADD COLUMN updated_at INTEGER DEFAULT 0;`,
    `ALTER TABLE health_records ADD COLUMN updated_at INTEGER DEFAULT 0;`,

    // staff
    `ALTER TABLE staff ADD COLUMN gender TEXT;`,
    `ALTER TABLE staff ADD COLUMN assigned_class_or_dept TEXT;`,
    `ALTER TABLE staff ADD COLUMN assigned_duty TEXT;`,
    `ALTER TABLE staff ADD COLUMN email TEXT;`,
    `ALTER TABLE staff ADD COLUMN hygiene_cert_date TEXT;`,
    `ALTER TABLE staff ADD COLUMN food_safety_cert_date TEXT;`,
    `ALTER TABLE staff ADD COLUMN health_check_date TEXT;`,
    `ALTER TABLE staff ADD COLUMN health_check_expiry TEXT;`,
    `ALTER TABLE staff ADD COLUMN contract_status TEXT;`,
    `ALTER TABLE staff ADD COLUMN start_date TEXT;`,
    `ALTER TABLE staff ADD COLUMN status TEXT;`,
    `ALTER TABLE staff ADD COLUMN notes TEXT;`,
    `ALTER TABLE staff ADD COLUMN updated_at INTEGER DEFAULT 0;`,

    // lesson_plans
    `ALTER TABLE lesson_plans ADD COLUMN title TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN target_class TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN age_group TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN subject TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN topic TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN month TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN date_range TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN development_field TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN learning_objectives TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN activities_plan TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN preparation TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN approval_date TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN file_attachment_name TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN notes TEXT;`,
    `ALTER TABLE lesson_plans ADD COLUMN updated_at INTEGER DEFAULT 0;`,

    // teacher_salaries
    `ALTER TABLE teacher_salaries ADD COLUMN staff_id TEXT;`,
    `ALTER TABLE teacher_salaries ADD COLUMN assigned_class TEXT;`,
    `ALTER TABLE teacher_salaries ADD COLUMN bank_account TEXT;`,
    `ALTER TABLE teacher_salaries ADD COLUMN bank_name TEXT;`,
    `ALTER TABLE teacher_salaries ADD COLUMN notes TEXT;`,
    `ALTER TABLE teacher_salaries ADD COLUMN updated_at INTEGER DEFAULT 0;`,

    // finance_transactions
    `ALTER TABLE finance_transactions ADD COLUMN receipt_number TEXT;`,
    `ALTER TABLE finance_transactions ADD COLUMN notes TEXT;`,
    `ALTER TABLE finance_transactions ADD COLUMN is_automatic_sync INTEGER DEFAULT 0;`,
    `ALTER TABLE finance_transactions ADD COLUMN updated_at INTEGER DEFAULT 0;`,

    // dish_breakdowns & dish_library
    `ALTER TABLE dish_breakdowns ADD COLUMN updated_at INTEGER DEFAULT 0;`,
    `ALTER TABLE dish_library ADD COLUMN is_favorite INTEGER DEFAULT 0;`,
    `ALTER TABLE dish_library ADD COLUMN ingredients_json TEXT;`,
    `ALTER TABLE dish_library ADD COLUMN updated_at INTEGER DEFAULT 0;`,
  ];

  for (const mig of migrations) {
    try {
      await db.execute(mig);
    } catch {
      // Column already exists, safe to ignore
    }
  }
}
