import {
  SchoolInfo,
  Step1Record,
  Step2Record,
  Step3Record,
  MenuItem,
  SampleDisposalRecord,
  StudentRecord,
  HealthRecord,
  StaffRecord,
  LessonPlanRecord,
  TeacherSalaryRecord,
  FinanceTransaction,
} from '@/types/preschool';

export const initialSchoolInfo: SchoolInfo = {
  name: 'MẦM NON TƯ THỤC ĐẢO TÍ HON',
  department: 'PHÒNG GIÁO DỤC VÀ ĐÀO TẠO XÃ LIÊN HƯƠNG',
  address: 'Xã Liên Hương, Huyện Tuy Phong, Tỉnh Bình Thuận',
  phone: '0913 456 789',
  academicYear: 'Năm học 2024 - 2025',
  principalName: 'VÕ THỊ HỒNG SIM',
  medicalStaffName: 'HUỲNH THỊ NGỌC NHI',
  headChefName: 'HUỲNH THỊ HOA',
  inspectorName: 'THANH XUÂN',
  receiverName: 'HUỲNH THỊ HOA',
  sampleKeeperName: 'HUỲNH THỊ HOA',
  sampleDisposerName: 'HUỲNH THỊ HOA',
  defaultPrintOrientation: 'landscape',
  // Nhân sự Ký tên Biểu mẫu & Báo cáo Hành chính
  creatorName: 'THANH XUÂN',
  teamLeaderNutritionName: 'HUỲNH THỊ HOA',
  teamLeaderEducationName: 'THANH XUÂN',
  vicePrincipalName: 'VÕ THỊ HỒNG SIM',
  accountantName: 'THANH XUÂN',
  // Nhà cung cấp thực phẩm tươi sống
  meatSupplierName: 'Đại lý Thực phẩm Sạch Liên Hương',
  meatSupplierAddress: 'Chợ Liên Hương, Xã Liên Hương - ĐT: 0918.234.567',
  meatDelivererName: 'Trần Văn Hưng',
  vegSupplierName: 'Vựa Rau củ quả An Toàn Liên Hương',
  vegSupplierAddress: 'Xã Liên Hương - ĐT: 0988.112.233',
  vegDelivererName: 'Nguyễn Văn Tâm',
  seafoodSupplierName: 'Vựa Thủy Hải Sản Tươi Sống Liên Hương',
  seafoodSupplierAddress: 'Khu phố 1, Xã Liên Hương - ĐT: 0912.889.900',
  seafoodDelivererName: 'Lê Văn Hoàng',
  // Nhà cung cấp thực phẩm khô
  dryProducerName: 'Nhà máy Phân phối Thực phẩm Bình Thuận',
  dryProducerAddress: 'Tuy Phong, Bình Thuận',
  drySupplierName: 'Cửa hàng Bách Hóa Tổng Hợp Liên Hương',
  drySupplierAddress: 'Trung tâm Xã Liên Hương - ĐT: 0252.385.1234',
  dryDelivererName: 'Đặng Văn Long',
};

export const initialStep1Records: Step1Record[] = [
  {
    id: 's1-1',
    date: '2025-05-15',
    time: '06:30',
    foodName: 'Thịt lợn nạc vai sinh học',
    category: 'Thịt cá tươi sống',
    quantity: '25.5 kg',
    sensoryQuality: 'Đạt (tươi mới, không mùi lạ)',
    supplier: 'Đại lý Thực phẩm Sạch Liên Hương',
    expiryOrCertificate: 'HĐ 0542 - Giấy kiểm dịch số 88/TY-BT',
    deliverer: 'Trần Văn Hưng',
    inspector: 'Thanh Xuân (Người kiểm tra)',
    result: 'Đạt nhập kho',
    notes: 'Thịt có dấu kiểm dịch thú y, màu hồng tươi, đàn hồi tốt',
  },
  {
    id: 's1-2',
    date: '2025-05-15',
    time: '06:45',
    foodName: 'Rau mồng tơi & mướp hương VietGAP',
    category: 'Rau củ quả',
    quantity: '18.0 kg',
    sensoryQuality: 'Đạt (tươi mới, không mùi lạ)',
    supplier: 'Vựa Rau củ quả An Toàn Liên Hương',
    expiryOrCertificate: 'Chứng nhận VietGAP số 112/VG',
    deliverer: 'Nguyễn Văn Tâm',
    inspector: 'Huỳnh Thị Hoa (Cấp dưỡng)',
    result: 'Đạt nhập kho',
    notes: 'Rau tươi, không dập nát, không có sâu bệnh',
  },
  {
    id: 's1-3',
    date: '2025-05-15',
    time: '07:00',
    foodName: 'Cá quả phi lê tươi sống',
    category: 'Thịt cá tươi sống',
    quantity: '14.0 kg',
    sensoryQuality: 'Đạt (tươi mới, không mùi lạ)',
    supplier: 'Vựa Thủy Hải Sản Tươi Sống Liên Hương',
    expiryOrCertificate: 'HĐ bán lẻ số 7712 - Cam kết an toàn',
    deliverer: 'Lê Văn Hoàng',
    inspector: 'Thanh Xuân (Người kiểm tra)',
    result: 'Đạt nhập kho',
    notes: 'Cá tươi, thớ thịt săn chắc, bảo quản thùng lạnh 3°C',
  },
  {
    id: 's1-4',
    date: '2025-05-15',
    time: '07:15',
    foodName: 'Sữa tươi tiệt trùng Vinamilk 180ml',
    category: 'Sữa & chế phẩm',
    quantity: '220 hộp',
    sensoryQuality: 'Đạt (tươi mới, không mùi lạ)',
    supplier: 'Cửa hàng Bách Hóa Tổng Hợp Liên Hương',
    expiryOrCertificate: 'HSD: 15/11/2025 - Lô NX441',
    deliverer: 'Đặng Văn Long',
    inspector: 'Huỳnh Thị Hoa (Cấp dưỡng)',
    result: 'Đạt nhập kho',
    notes: 'Vỏ hộp nguyên vẹn, không móp méo',
  },
  {
    id: 's1-5',
    date: '2025-05-14',
    time: '06:35',
    foodName: 'Đậu phụ tươi làm trong ngày',
    category: 'Thực phẩm chế biến ngay',
    quantity: '12 kg (40 bìa)',
    sensoryQuality: 'Đạt (tươi mới, không mùi lạ)',
    supplier: 'Cơ sở sản xuất Đậu Hũ Liên Hương',
    expiryOrCertificate: 'SX trong ngày 14/05/2025',
    deliverer: 'Đỗ Văn Cường',
    inspector: 'Thanh Xuân (Người kiểm tra)',
    result: 'Đạt nhập kho',
    notes: 'Đậu thơm mềm, nóng ấm, không có vị chua',
  } as any,
];

export const initialStep2Records: Step2Record[] = [
  {
    id: 's2-1',
    date: '2025-05-15',
    meal: 'Bữa trưa',
    dishName: 'Thịt lợn băm rim sốt cà chua',
    prepTime: '08:00 - 09:15',
    cookTime: '09:30 - 10:15',
    cookingTemp: '100°C (nấu sôi kỹ 20 phút)',
    hygieneStatus: 'Đạt vệ sinh ATTP',
    chef: 'Huỳnh Thị Hoa',
    supervisor: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    result: 'Đạt chuẩn vào phục vụ',
    notes: 'Dụng cụ dao thớt riêng biệt cho đồ sống và chín',
  },
  {
    id: 's2-2',
    date: '2025-05-15',
    meal: 'Bữa trưa',
    dishName: 'Canh rau mồng tơi nấu thịt nạc băm',
    prepTime: '08:30 - 09:20',
    cookTime: '10:00 - 10:30',
    cookingTemp: '100°C (sôi bùng 10 phút)',
    hygieneStatus: 'Đạt vệ sinh ATTP',
    chef: 'Huỳnh Thị Hoa',
    supervisor: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    result: 'Đạt chuẩn vào phục vụ',
    notes: 'Rau rửa 3 nước sạch ngâm nước muối loãng trước khi nấu',
  },
  {
    id: 's2-3',
    date: '2025-05-15',
    meal: 'Bữa trưa',
    dishName: 'Cơm trắng gạo dẻo thơm',
    prepTime: '09:00 - 09:20',
    cookTime: '09:30 - 10:30',
    cookingTemp: 'Tủ hấp cơm công nghiệp 100°C',
    hygieneStatus: 'Đạt vệ sinh ATTP',
    chef: 'Huỳnh Thị Hoa',
    supervisor: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    result: 'Đạt chuẩn vào phục vụ',
    notes: 'Cơm chín dẻo, mềm, thơm, phù hợp khẩu vị trẻ mầm non',
  },
  {
    id: 's2-4',
    date: '2025-05-15',
    meal: 'Bữa phụ xế',
    dishName: 'Cháo gà đậu xanh hạt sen',
    prepTime: '12:30 - 13:15',
    cookTime: '13:30 - 14:45',
    cookingTemp: 'Nấu nhừ 100°C',
    hygieneStatus: 'Đạt vệ sinh ATTP',
    chef: 'Huỳnh Thị Hoa',
    supervisor: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    result: 'Đạt chuẩn vào phục vụ',
    notes: 'Cháo nhuyễn mịn, gà xé nhỏ phù hợp độ tuổi',
  },
];

export const initialStep3Records: Step3Record[] = [
  {
    id: 's3-1',
    date: '2025-05-15',
    time: '10:30',
    meal: 'Bữa trưa',
    dishName: 'Thịt lợn băm rim sốt cà chua',
    sensoryEvaluation: 'Màu sắc tươi, mùi vị thơm ngon tự nhiên, chín kỹ',
    servingTemp: '72°C',
    sampleWeight: '150g',
    storageLocation: 'Tủ lưu mẫu số 01 - Ngăn 1 (3°C)',
    taster: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    keeper: 'Huỳnh Thị Hoa (Cấp dưỡng)',
    result: 'Đủ điều kiện cho trẻ ăn',
    notes: 'Vị vừa vặn, màu sắc hấp dẫn, đủ điều kiện phục vụ các lớp',
  },
  {
    id: 's3-2',
    date: '2025-05-15',
    time: '10:30',
    meal: 'Bữa trưa',
    dishName: 'Canh rau mồng tơi nấu thịt',
    sensoryEvaluation: 'Màu sắc tươi, mùi vị thơm ngon tự nhiên, chín kỹ',
    servingTemp: '68°C',
    sampleWeight: '150g (nước + cái)',
    storageLocation: 'Tủ lưu mẫu số 01 - Ngăn 1 (3°C)',
    taster: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    keeper: 'Huỳnh Thị Hoa (Cấp dưỡng)',
    result: 'Đủ điều kiện cho trẻ ăn',
    notes: 'Rau xanh, nước canh trong ngọt tự nhiên',
  },
  {
    id: 's3-3',
    date: '2025-05-15',
    time: '10:30',
    meal: 'Bữa trưa',
    dishName: 'Cơm trắng dẻo thơm',
    sensoryEvaluation: 'Màu sắc tươi, mùi vị thơm ngon tự nhiên, chín kỹ',
    servingTemp: '75°C',
    sampleWeight: '150g',
    storageLocation: 'Tủ lưu mẫu số 01 - Ngăn 1 (3°C)',
    taster: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    keeper: 'Huỳnh Thị Hoa (Cấp dưỡng)',
    result: 'Đủ điều kiện cho trẻ ăn',
    notes: 'Cơm dẻo mềm, không sượng',
  },
  {
    id: 's3-4',
    date: '2025-05-15',
    time: '14:45',
    meal: 'Bữa phụ xế',
    dishName: 'Cháo gà đậu xanh hạt sen',
    sensoryEvaluation: 'Màu sắc tươi, mùi vị thơm ngon tự nhiên, chín kỹ',
    servingTemp: '65°C',
    sampleWeight: '150g',
    storageLocation: 'Tủ lưu mẫu số 01 - Ngăn 2 (3°C)',
    taster: 'Thanh Xuân (Giáo viên)',
    keeper: 'Huỳnh Thị Hoa (Cấp dưỡng)',
    result: 'Đủ điều kiện cho trẻ ăn',
    notes: 'Thơm bùi của hạt sen và đậu xanh, thịt gà chín nhừ',
  },
];

export const initialMenuItems: MenuItem[] = [
  {
    id: 'm-1',
    weekNumber: 36,
    month: '05/2025',
    ageGroup: 'Mẫu giáo Lớn (5-6 tuổi)',
    dayOfWeek: 'Thứ Hai',
    breakfast: 'Phở bò - Sữa tươi tiệt trùng',
    snackMorning: 'Nước cam tươi mật ong',
    lunchMain: 'Thịt lợn rim ngũ vị - Trứng cút luộc kho tàu',
    lunchSoup: 'Canh cua đồng mồng tơi mướp',
    lunchStaple: 'Cơm tám thơm',
    lunchDessert: 'Chuối tiêu chín tráng miệng',
    afternoonSnack: 'Cháo cá hồi bí đỏ phô mai',
    caloriesKcal: 780,
    proteinRatio: '14-16% Pro, 25-30% Lipid, 55-60% Glucid',
    status: 'Đã phê duyệt',
    approvedBy: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    notes: 'Thực đơn đạt chuẩn khuyến nghị Viện Dinh Dưỡng Bộ Y tế',
  },
  {
    id: 'm-2',
    weekNumber: 36,
    month: '05/2025',
    ageGroup: 'Mẫu giáo Lớn (5-6 tuổi)',
    dayOfWeek: 'Thứ Ba',
    breakfast: 'Bánh cuốn chả lụa nóng',
    snackMorning: 'Sữa chua men sống Yakult',
    lunchMain: 'Tôm nõn sốt chua ngọt',
    lunchSoup: 'Canh sườn hầm củ dền cà rốt',
    lunchStaple: 'Cơm tám thơm',
    lunchDessert: 'Dưa hấu đỏ',
    afternoonSnack: 'Bún mọc sườn non nấm hương',
    caloriesKcal: 795,
    proteinRatio: '15% Pro, 28% Lipid, 57% Glucid',
    status: 'Đã phê duyệt',
    approvedBy: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    notes: 'Tăng cường chất xơ và vitamin C',
  },
  {
    id: 'm-3',
    weekNumber: 36,
    month: '05/2025',
    ageGroup: 'Mẫu giáo Lớn (5-6 tuổi)',
    dayOfWeek: 'Thứ Tư',
    breakfast: 'Xôi gấc hạt sen rắc vừng',
    snackMorning: 'Sữa đậu nành mè đen',
    lunchMain: 'Thịt bò xào củ quả ngũ sắc',
    lunchSoup: 'Canh ngao nấu chua dứa cà chua',
    lunchStaple: 'Cơm tám thơm',
    lunchDessert: 'Thanh long ruột đỏ',
    afternoonSnack: 'Chè đậu đỏ yến mạch cốt dừa',
    caloriesKcal: 810,
    proteinRatio: '15% Pro, 26% Lipid, 59% Glucid',
    status: 'Đã phê duyệt',
    approvedBy: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    notes: 'Cung cấp sắt và khoáng chất dồi dào',
  },
  {
    id: 'm-4',
    weekNumber: 36,
    month: '05/2025',
    ageGroup: 'Mẫu giáo Lớn (5-6 tuổi)',
    dayOfWeek: 'Thứ Năm',
    breakfast: 'Bánh mỳ gối phết bơ mứt dâu & Sữa tươi',
    snackMorning: 'Nước ép ổi táo tươi',
    lunchMain: 'Cá quả tẩm bột chiên xù',
    lunchSoup: 'Canh bí xanh nấu tôm khô',
    lunchStaple: 'Cơm tám thơm',
    lunchDessert: 'Đu đủ chín ngọt',
    afternoonSnack: 'Cháo sườn non hạt sen',
    caloriesKcal: 775,
    proteinRatio: '14% Pro, 27% Lipid, 59% Glucid',
    status: 'Đã phê duyệt',
    approvedBy: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    notes: 'Thực phẩm mềm dễ tiêu hóa',
  },
  {
    id: 'm-5',
    weekNumber: 36,
    month: '05/2025',
    ageGroup: 'Mẫu giáo Lớn (5-6 tuổi)',
    dayOfWeek: 'Thứ Sáu',
    breakfast: 'Mì nui thịt băm sốt cà chua',
    snackMorning: 'Sữa chua uống Probi',
    lunchMain: 'Gà hấp lá chanh xé nhỏ',
    lunchSoup: 'Canh rau ngót nấu giò sống',
    lunchStaple: 'Cơm tám thơm',
    lunchDessert: 'Quýt đường ngọt thanh',
    afternoonSnack: 'Bánh bao hấp nhân thịt trứng cút',
    caloriesKcal: 820,
    proteinRatio: '16% Pro, 28% Lipid, 56% Glucid',
    status: 'Đã phê duyệt',
    approvedBy: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    notes: 'Tổng kết tuần thực đơn đạt năng lượng tiêu chuẩn',
  },
];

export const initialSampleDisposalRecords: SampleDisposalRecord[] = [
  {
    id: 'disp-1',
    dateSampled: '2025-05-14',
    timeSampled: '10:30',
    meal: 'Bữa trưa',
    dishName: 'Thịt bò xào đậu Hà Lan',
    sampleWeight: '120g',
    containerType: 'Hộp Inox có nắp vô trùng',
    storageTemp: '3.5°C',
    disposalDate: '2025-05-15',
    disposalTime: '10:45',
    conditionAtDisposal: 'Bình thường, không biến chất',
    samplerName: 'Huỳnh Thị Hoa (Cấp dưỡng)',
    witnessName: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    status: 'Đã hủy mẫu theo quy định',
    notes: 'Đã lưu đủ 24h, niêm phong nguyên vẹn trước khi tiêu hủy',
  },
  {
    id: 'disp-2',
    dateSampled: '2025-05-14',
    timeSampled: '10:30',
    meal: 'Bữa trưa',
    dishName: 'Canh ngao nấu chua mồng tơi',
    sampleWeight: '150g',
    containerType: 'Hộp Inox có nắp vô trùng',
    storageTemp: '3.5°C',
    disposalDate: '2025-05-15',
    disposalTime: '10:45',
    conditionAtDisposal: 'Bình thường, không biến chất',
    samplerName: 'Huỳnh Thị Hoa (Cấp dưỡng)',
    witnessName: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    status: 'Đã hủy mẫu theo quy định',
    notes: 'Hủy mẫu bằng dung dịch khử trùng theo quy định',
  },
  {
    id: 'disp-3',
    dateSampled: '2025-05-15',
    timeSampled: '10:30',
    meal: 'Bữa trưa',
    dishName: 'Thịt lợn băm rim sốt cà chua',
    sampleWeight: '150g',
    containerType: 'Hộp Inox có nắp vô trùng',
    storageTemp: '3.0°C',
    disposalDate: '2025-05-16',
    disposalTime: '10:30',
    conditionAtDisposal: 'Bình thường, không biến chất',
    samplerName: 'Huỳnh Thị Hoa (Cấp dưỡng)',
    witnessName: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    status: 'Đang lưu mẫu (<24h)',
    notes: 'Đang lưu tại tủ lưu mẫu số 01, niêm phong kẹp chì',
  },
  {
    id: 'disp-4',
    dateSampled: '2025-05-15',
    timeSampled: '14:45',
    meal: 'Bữa phụ xế',
    dishName: 'Cháo gà đậu xanh hạt sen',
    sampleWeight: '150g',
    containerType: 'Hộp Inox có nắp vô trùng',
    storageTemp: '3.0°C',
    disposalDate: '2025-05-16',
    disposalTime: '14:45',
    conditionAtDisposal: 'Bình thường, không biến chất',
    samplerName: 'Huỳnh Thị Hoa (Cấp dưỡng)',
    witnessName: 'Thanh Xuân (Giáo viên)',
    status: 'Đang lưu mẫu (<24h)',
    notes: 'Thời hạn lưu đến 14h45 ngày mai 16/05/2025',
  },
];

export const initialStudents: StudentRecord[] = [
  {
    id: 'st-1',
    studentCode: 'MN-2024-001',
    fullName: 'Nguyễn Gia Bảo',
    dob: '2019-03-15',
    gender: 'Nam',
    className: 'Lá 1',
    parentName: 'Nguyễn Thành Long',
    parentPhone: '0988 123 456',
    address: 'Khu phố 1, Xã Liên Hương, Tuy Phong',
    attendanceStatus: 'Có mặt',
    allergiesOrDiet: 'Không có dị ứng',
    enrollmentDate: '2022-09-05',
    notes: 'Ngoan, tích cực tham gia hoạt động nhóm',
  },
  {
    id: 'st-2',
    studentCode: 'MN-2024-002',
    fullName: 'Trần Thảo Linh',
    dob: '2019-07-22',
    gender: 'Nữ',
    className: 'Lá 1',
    parentName: 'Trần Thị Thúy',
    parentPhone: '0977 234 567',
    address: 'Khu phố 3, Xã Liên Hương, Tuy Phong',
    attendanceStatus: 'Có mặt',
    allergiesOrDiet: 'Dị ứng phấn hoa nhẹ',
    enrollmentDate: '2022-09-05',
    notes: 'Khéo tay, vẽ tranh rất đẹp',
  },
  {
    id: 'st-3',
    studentCode: 'MN-2024-003',
    fullName: 'Lê Minh Khôi',
    dob: '2020-04-10',
    gender: 'Nam',
    className: 'Chồi 1',
    parentName: 'Lê Tuấn Hưng',
    parentPhone: '0912 345 678',
    address: 'Khu phố 2, Xã Liên Hương, Tuy Phong',
    attendanceStatus: 'Nghỉ có phép',
    allergiesOrDiet: 'Dị ứng hải sản (tôm, cua)',
    enrollmentDate: '2023-09-05',
    notes: 'Gia đình xin nghỉ khám răng 1 ngày',
  },
  {
    id: 'st-4',
    studentCode: 'MN-2024-004',
    fullName: 'Phạm Bảo Trâm',
    dob: '2020-11-05',
    gender: 'Nữ',
    className: 'Chồi 2',
    parentName: 'Hoàng Bích Phương',
    parentPhone: '0904 567 890',
    address: 'Khu phố 4, Xã Liên Hương, Tuy Phong',
    attendanceStatus: 'Có mặt',
    allergiesOrDiet: 'Không dung nạp đường lactose (uống sữa hạt riêng)',
    enrollmentDate: '2023-09-05',
    notes: 'Phụ huynh gửi sữa hạt riêng hàng ngày',
  },
  {
    id: 'st-5',
    studentCode: 'MN-2024-005',
    fullName: 'Vũ Đăng Khoa',
    dob: '2021-02-18',
    gender: 'Nam',
    className: 'Mầm 1',
    parentName: 'Vũ Quốc Anh',
    parentPhone: '0936 678 901',
    address: 'Khu phố 1, Xã Liên Hương, Tuy Phong',
    attendanceStatus: 'Có mặt',
    allergiesOrDiet: 'Không có dị ứng',
    enrollmentDate: '2024-09-05',
    notes: 'Thích chơi xếp hình lego và đọc thơ',
  },
  {
    id: 'st-6',
    studentCode: 'MN-2024-006',
    fullName: 'Đỗ Tuệ An',
    dob: '2022-05-20',
    gender: 'Nữ',
    className: 'Nhà Trẻ Hoa Cúc',
    parentName: 'Nguyễn Thị Ngọc',
    parentPhone: '0983 789 012',
    address: 'Khu phố 5, Xã Liên Hương, Tuy Phong',
    attendanceStatus: 'Có mặt',
    allergiesOrDiet: 'Không có dị ứng',
    enrollmentDate: '2024-09-05',
    notes: 'Ăn ngủ tốt, thích nghe nhạc thiếu nhi',
  },
];

export const initialHealthRecords: HealthRecord[] = [
  {
    id: 'hr-1',
    studentId: 'st-1',
    studentName: 'Nguyễn Gia Bảo',
    className: 'Lá 1',
    checkDate: '2025-04-20',
    heightCm: 114.5,
    weightKg: 20.2,
    nutritionStatus: 'Bình thường (Kênh A)',
    vaccinationStatus: 'Đầy đủ theo độ tuổi',
    generalHealth: 'Tốt',
    doctorOrExaminer: 'Huỳnh Thị Ngọc Nhi (Bảo mẫu / Y tế)',
    notes: 'Tăng trưởng thể chất đạt chuẩn WHO',
  },
  {
    id: 'hr-2',
    studentId: 'st-2',
    studentName: 'Trần Thảo Linh',
    className: 'Lá 1',
    checkDate: '2025-04-20',
    heightCm: 112.0,
    weightKg: 18.5,
    nutritionStatus: 'Bình thường (Kênh A)',
    vaccinationStatus: 'Đầy đủ theo độ tuổi',
    generalHealth: 'Tốt',
    doctorOrExaminer: 'Huỳnh Thị Ngọc Nhi (Bảo mẫu / Y tế)',
    notes: 'Răng sữa tốt, không sâu răng',
  },
  {
    id: 'hr-3',
    studentId: 'st-3',
    studentName: 'Lê Minh Khôi',
    className: 'Chồi 1',
    checkDate: '2025-04-20',
    heightCm: 104.0,
    weightKg: 14.8,
    nutritionStatus: 'Suy dinh dưỡng thể nhẹ cân',
    vaccinationStatus: 'Đầy đủ theo độ tuổi',
    generalHealth: 'Cần theo dõi',
    doctorOrExaminer: 'Huỳnh Thị Ngọc Nhi (Bảo mẫu / Y tế)',
    notes: 'Tư vấn phụ huynh tăng cường bữa phụ giàu đạm kẽm',
  },
  {
    id: 'hr-4',
    studentId: 'st-4',
    studentName: 'Phạm Bảo Trâm',
    className: 'Chồi 2',
    checkDate: '2025-04-20',
    heightCm: 106.5,
    weightKg: 21.0,
    nutritionStatus: 'Nguy cơ béo phì / Béo phì',
    vaccinationStatus: 'Đầy đủ theo độ tuổi',
    generalHealth: 'Cần theo dõi',
    doctorOrExaminer: 'Huỳnh Thị Ngọc Nhi (Bảo mẫu / Y tế)',
    notes: 'Hạn chế đồ ngọt, tăng vận động thể chất ngoài trời',
  },
  {
    id: 'hr-5',
    studentId: 'st-5',
    studentName: 'Vũ Đăng Khoa',
    className: 'Mầm 1',
    checkDate: '2025-04-20',
    heightCm: 97.0,
    weightKg: 15.1,
    nutritionStatus: 'Bình thường (Kênh A)',
    vaccinationStatus: 'Đầy đủ theo độ tuổi',
    generalHealth: 'Tốt',
    doctorOrExaminer: 'Huỳnh Thị Ngọc Nhi (Bảo mẫu / Y tế)',
    notes: 'Thể lực dẻo dai, nhanh nhẹn',
  },
];

export const initialStaffRecords: StaffRecord[] = [
  {
    id: 'stf-1',
    staffCode: 'CB-001',
    fullName: 'Võ Thị Hồng Sim',
    gender: 'Nữ',
    role: 'Chủ cơ sở / Quản lý chung',
    qualification: 'Cử nhân Quản lý Giáo dục Mầm non',
    assignedClassOrDept: 'Ban Giám hiệu - Quản lý cơ sở',
    phone: '0913 456 789',
    hygieneCertDate: '2024-08-15',
    healthCheckDate: '2025-03-10',
    status: 'Đang công tác',
    notes: 'Chủ cơ sở Mầm Non Tư Thục Đảo Tí Hon',
  },
  {
    id: 'stf-2',
    staffCode: 'CB-002',
    fullName: 'Thanh Xuân',
    gender: 'Nữ',
    role: 'Giáo viên phụ trách lớp',
    qualification: 'Cử nhân Sư phạm Mầm non',
    assignedClassOrDept: 'Chủ nhiệm Lớp Mầm & Người lập biểu',
    phone: '0982 123 456',
    hygieneCertDate: '2024-08-15',
    healthCheckDate: '2025-03-10',
    status: 'Đang công tác',
    notes: 'Giáo viên tận tâm, kiêm phụ trách hồ sơ biểu mẫu',
  },
  {
    id: 'stf-3',
    staffCode: 'CB-003',
    fullName: 'Huỳnh Thị Hoa',
    gender: 'Nữ',
    role: 'Cấp dưỡng',
    qualification: 'Chứng chỉ Kỹ thuật Chế biến Món ăn & ATTP',
    assignedClassOrDept: 'Khu vực Bếp ăn bán trú Đảo Tí Hon',
    phone: '0904 556 789',
    hygieneCertDate: '2024-08-15',
    healthCheckDate: '2025-03-10',
    status: 'Đang công tác',
    notes: 'Cấp dưỡng chính, quản lý vệ sinh ATTP và lưu mẫu',
  },
  {
    id: 'stf-4',
    staffCode: 'CB-004',
    fullName: 'Huỳnh Thị Ngọc Nhi',
    gender: 'Nữ',
    role: 'Bảo mẫu',
    qualification: 'Chứng chỉ Nghiệp vụ Bảo mẫu & Sơ cấp cứu',
    assignedClassOrDept: 'Tổ Chăm sóc & Y tế Học đường',
    phone: '0973 112 233',
    hygieneCertDate: '2024-08-15',
    healthCheckDate: '2025-03-10',
    status: 'Đang công tác',
    notes: 'Bảo mẫu chăm sóc trẻ chu đáo, hỗ trợ y tế học sinh',
  },
];

export const initialLessonPlans: LessonPlanRecord[] = [
  {
    id: 'lp-1',
    title: 'Khám phá thế giới Động vật biển quê hương Liên Hương: Chú rùa biển',
    theme: 'Chủ đề: Thế giới động vật (Tuần 3)',
    targetClass: 'Khối Mầm (3-4 tuổi)',
    teacherName: 'Thanh Xuân',
    weekNumber: 32,
    dateRange: '12/05/2025 - 16/05/2025',
    developmentField: 'Phát triển Nhận thức',
    approvalStatus: 'Đã phê duyệt',
    approverName: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    approvalDate: '2025-05-10',
    fileAttachmentName: 'GiaoAn_RuaBien_KhoiMam.pdf',
    notes: 'Mục tiêu: Nhận biết đặc điểm rùa biển, tình yêu thiên nhiên biển đảo',
  },
  {
    id: 'lp-2',
    title: 'Vận động cơ bản: Bật qua vạch kẻ - Trò chơi: Cá lớn nuốt cá bé',
    theme: 'Chủ đề: Bé khỏe bé ngoan',
    targetClass: 'Khối Chồi (4-5 tuổi)',
    teacherName: 'Thanh Xuân',
    weekNumber: 32,
    dateRange: '12/05/2025 - 16/05/2025',
    developmentField: 'Phát triển Thể chất',
    approvalStatus: 'Đã phê duyệt',
    approverName: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    approvalDate: '2025-05-10',
    fileAttachmentName: 'TheChat_BatQuaVach_KhoiChoi.pdf',
    notes: 'Tập đúng kỹ thuật tiếp đất bằng mũi bàn chân êm ái',
  },
  {
    id: 'lp-3',
    title: 'Làm quen chữ cái: Nhận biết và phát âm nhóm chữ s, x',
    theme: 'Chủ đề: Quê hương Liên Hương tươi đẹp',
    targetClass: 'Khối Lá (5-6 tuổi)',
    teacherName: 'Thanh Xuân',
    weekNumber: 33,
    dateRange: '19/05/2025 - 23/05/2025',
    developmentField: 'Phát triển Ngôn ngữ',
    approvalStatus: 'Đã phê duyệt',
    approverName: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    approvalDate: '2025-05-11',
    fileAttachmentName: 'NgonNgu_ChuCai_S_X_KhoiLa.docx',
    notes: 'Chuẩn bị tâm thế sẵn sàng vào lớp 1 cho trẻ 5 tuổi',
  },
  {
    id: 'lp-4',
    title: 'Giáo dục kỹ năng sống: Nói lời cảm ơn và xin lỗi đúng lúc',
    theme: 'Chủ đề: Bé và những người bạn',
    targetClass: 'Khối Chồi (4-5 tuổi)',
    teacherName: 'Thanh Xuân',
    weekNumber: 33,
    dateRange: '19/05/2025 - 23/05/2025',
    developmentField: 'Phát triển Tình cảm - Kỹ năng XH',
    approvalStatus: 'Đã phê duyệt',
    approverName: 'Võ Thị Hồng Sim (Chủ cơ sở)',
    approvalDate: '2025-05-11',
    fileAttachmentName: 'KyNang_CamOn_XinLoi.pdf',
    notes: 'Ứng dụng thực hành tình huống trực tiếp trên lớp',
  },
];

// Dữ liệu bảng lương giáo viên & nhân viên mẫu
export const initialSalaries: TeacherSalaryRecord[] = [
  {
    id: 'sal-1',
    staffId: 'stf-2',
    staffName: 'Thanh Xuân',
    role: 'Giáo viên phụ trách lớp',
    assignedClass: 'Lớp Mầm 1 (3-4 tuổi)',
    month: '2025-05',
    baseSalary: 7000000,
    allowanceResponsibility: 1500000,
    allowanceLunch: 730000,
    allowanceOther: 500000,
    bonus: 800000,
    insuranceDeduction: 735000,
    advancePayment: 0,
    otherDeductions: 0,
    workDaysStandard: 24,
    workDaysActual: 24,
    netSalary: 9795000,
    paymentStatus: 'Đã thanh toán',
    paymentMethod: 'Chuyển khoản ngân hàng',
    bankAccount: '19034567890012',
    bankName: 'Vietcombank',
    notes: 'Phụ trách chuyên môn giảng dạy & lập biểu mẫu',
  },
  {
    id: 'sal-2',
    staffId: 'stf-3',
    staffName: 'Huỳnh Thị Hoa',
    role: 'Cấp dưỡng',
    assignedClass: 'Bếp ăn bán trú Đảo Tí Hon',
    month: '2025-05',
    baseSalary: 6800000,
    allowanceResponsibility: 1500000,
    allowanceLunch: 730000,
    allowanceOther: 500000,
    bonus: 700000,
    insuranceDeduction: 714000,
    advancePayment: 0,
    otherDeductions: 0,
    workDaysStandard: 24,
    workDaysActual: 24,
    netSalary: 9516000,
    paymentStatus: 'Đã thanh toán',
    paymentMethod: 'Chuyển khoản ngân hàng',
    bankAccount: '1029384756',
    bankName: 'Agribank',
    notes: 'Cấp dưỡng chính, bếp ăn đạt chuẩn ATTP',
  },
  {
    id: 'sal-3',
    staffId: 'stf-4',
    staffName: 'Huỳnh Thị Ngọc Nhi',
    role: 'Bảo mẫu',
    assignedClass: 'Tổ Chăm sóc & Y tế',
    month: '2025-05',
    baseSalary: 6000000,
    allowanceResponsibility: 1000000,
    allowanceLunch: 730000,
    allowanceOther: 400000,
    bonus: 500000,
    insuranceDeduction: 630000,
    advancePayment: 0,
    otherDeductions: 0,
    workDaysStandard: 24,
    workDaysActual: 24,
    netSalary: 8000000,
    paymentStatus: 'Đã thanh toán',
    paymentMethod: 'Chuyển khoản ngân hàng',
    bankAccount: '0011002345678',
    bankName: 'Vietcombank',
    notes: 'Bảo mẫu chăm sóc trẻ & theo dõi y tế',
  },
  {
    id: 'sal-4',
    staffId: 'stf-1',
    staffName: 'Võ Thị Hồng Sim',
    role: 'Chủ cơ sở / Quản lý chung',
    assignedClass: 'Ban Quản lý Nhà trường',
    month: '2025-05',
    baseSalary: 8500000,
    allowanceResponsibility: 2000000,
    allowanceLunch: 730000,
    allowanceOther: 600000,
    bonus: 1000000,
    insuranceDeduction: 892500,
    advancePayment: 0,
    otherDeductions: 0,
    workDaysStandard: 24,
    workDaysActual: 24,
    netSalary: 11937500,
    paymentStatus: 'Đã thanh toán',
    paymentMethod: 'Chuyển khoản ngân hàng',
    bankAccount: '21510001239999',
    bankName: 'BIDV',
    notes: 'Quản lý điều hành cơ sở Mầm Non Đảo Tí Hon',
  },
];

// Dữ liệu Giao dịch Thu - Chi mẫu
export const initialTransactions: FinanceTransaction[] = [
  // CÁC KHOẢN THU THÁNG 5/2025
  {
    id: 'tx-thu-1',
    date: '2025-05-02',
    type: 'thu',
    category: 'Học phí hàng tháng',
    amount: 145000000,
    payerOrReceiver: 'Phụ huynh học sinh Mầm Non Tư Thục Đảo Tí Hon',
    method: 'Chuyển khoản',
    receiptNumber: 'PT-2025-05-01',
    notes: 'Thu học phí đợt 1 tháng 05/2025 (100 học sinh)',
  },
  {
    id: 'tx-thu-2',
    date: '2025-05-02',
    type: 'thu',
    category: 'Học phí hàng tháng',
    amount: 52500000,
    payerOrReceiver: 'Phụ huynh Khối Nhà Trẻ Đảo Tí Hon',
    method: 'Chuyển khoản',
    receiptNumber: 'PT-2025-05-02',
    notes: 'Thu học phí tháng 05/2025 (35 học sinh Nhà Trẻ)',
  },
  {
    id: 'tx-thu-3',
    date: '2025-05-02',
    type: 'thu',
    category: 'Tiền ăn bán trú của học sinh',
    amount: 114400000,
    payerOrReceiver: 'Phụ huynh học sinh bán trú (145 suất x 22 ngày)',
    method: 'Chuyển khoản',
    receiptNumber: 'PT-2025-05-03',
    notes: 'Tiền ăn bán trú tính theo mức 35.000đ/ngày',
  },
  {
    id: 'tx-thu-4',
    date: '2025-05-05',
    type: 'thu',
    category: 'Tiền chăm sóc ngoài giờ / Trông muộn',
    amount: 12800000,
    payerOrReceiver: 'Phụ huynh đăng ký dịch vụ ngoài giờ',
    method: 'Tiền mặt',
    receiptNumber: 'PT-2025-05-04',
    notes: 'Thu phí đón muộn và giữ trẻ thứ 7 tháng 5',
  },
  {
    id: 'tx-thu-5',
    date: '2025-05-08',
    type: 'thu',
    category: 'Ngoại khóa / Kỹ năng sống',
    amount: 21750000,
    payerOrReceiver: 'Phụ huynh đăng ký CLB Tiếng Anh & Vẽ sáng tạo',
    method: 'Chuyển khoản',
    receiptNumber: 'PT-2025-05-05',
    notes: 'CLB Tiếng Anh và Hoạt động năng khiếu',
  },

  // CÁC KHOẢN CHI THÁNG 5/2025
  {
    id: 'tx-chi-1',
    date: '2025-05-05',
    type: 'chi',
    category: 'Chi trả lương giáo viên & nhân viên',
    amount: 39248500,
    payerOrReceiver: 'Tập thể Cán bộ Giáo viên & Nhân viên (Võ Thị Hồng Sim, Thanh Xuân, Huỳnh Thị Hoa, Huỳnh Thị Ngọc Nhi)',
    method: 'Chuyển khoản',
    receiptNumber: 'PC-2025-05-01',
    notes: 'Thanh toán bảng lương tháng 05/2025',
  },
  {
    id: 'tx-chi-2',
    date: '2025-05-05',
    type: 'chi',
    category: 'Chi mua thực phẩm & Chợ hàng ngày',
    amount: 26850000,
    payerOrReceiver: 'Đại lý Thực phẩm Sạch & Vựa Rau củ Liên Hương',
    method: 'Chuyển khoản',
    receiptNumber: 'PC-2025-05-02',
    notes: 'Thanh toán tiền thịt cá, rau củ quả tuần 1 tháng 5',
    isAutomaticSync: true,
  },
  {
    id: 'tx-chi-3',
    date: '2025-05-12',
    type: 'chi',
    category: 'Chi mua thực phẩm & Chợ hàng ngày',
    amount: 27120000,
    payerOrReceiver: 'Đại lý Thực phẩm Sạch & Vựa Rau củ Liên Hương',
    method: 'Chuyển khoản',
    receiptNumber: 'PC-2025-05-03',
    notes: 'Thanh toán tiền thịt cá, rau củ quả tuần 2 tháng 5',
    isAutomaticSync: true,
  },
  {
    id: 'tx-chi-4',
    date: '2025-05-19',
    type: 'chi',
    category: 'Chi mua thực phẩm & Chợ hàng ngày',
    amount: 26940000,
    payerOrReceiver: 'Đại lý Thực phẩm Sạch & Vựa Rau củ Liên Hương',
    method: 'Chuyển khoản',
    receiptNumber: 'PC-2025-05-04',
    notes: 'Thanh toán tiền thịt cá, rau củ quả tuần 3 tháng 5',
    isAutomaticSync: true,
  },
  {
    id: 'tx-chi-5',
    date: '2025-05-26',
    type: 'chi',
    category: 'Chi mua thực phẩm & Chợ hàng ngày',
    amount: 27300000,
    payerOrReceiver: 'Đại lý Thực phẩm Sạch & Vựa Rau củ Liên Hương',
    method: 'Chuyển khoản',
    receiptNumber: 'PC-2025-05-05',
    notes: 'Thanh toán tiền thịt cá, rau củ quả tuần 4 tháng 5',
    isAutomaticSync: true,
  },
  {
    id: 'tx-chi-6',
    date: '2025-05-10',
    type: 'chi',
    category: 'Chi điện, nước, internet, gas bếp',
    amount: 14250000,
    payerOrReceiver: 'Điện Lực Tuy Phong & Nước Sinh Hoạt Liên Hương',
    method: 'Chuyển khoản',
    receiptNumber: 'PC-2025-05-06',
    notes: 'Hóa đơn tiền điện, nước sinh hoạt, bình gas công nghiệp tháng 5',
  },
  {
    id: 'tx-chi-7',
    date: '2025-05-15',
    type: 'chi',
    category: 'Chi mua đồ dùng, giáo cụ, đồ chơi mầm non',
    amount: 8600000,
    payerOrReceiver: 'Công ty Thiết bị Giáo dục Mầm non',
    method: 'Chuyển khoản',
    receiptNumber: 'PC-2025-05-07',
    notes: 'Mua bổ sung đất nặn an toàn, giấy vẽ màu, khối xếp hình',
  },
  {
    id: 'tx-chi-8',
    date: '2025-05-20',
    type: 'chi',
    category: 'Chi y tế, thuốc men, sát khuẩn trường',
    amount: 3200000,
    payerOrReceiver: 'Nhà thuốc Liên Hương & Vật tư Y tế',
    method: 'Tiền mặt',
    receiptNumber: 'PC-2025-05-08',
    notes: 'Nước sát khuẩn Cloramin B, bông gạc, vitamin tổng hợp cho tủ y tế',
  },
  {
    id: 'tx-chi-9',
    date: '2025-05-28',
    type: 'chi',
    category: 'Chi liên hoan, quà lễ tết, khen thưởng bé',
    amount: 12500000,
    payerOrReceiver: 'Ban Phụ Huynh & Nhà sách Liên Hương',
    method: 'Tiền mặt',
    receiptNumber: 'PC-2025-05-09',
    notes: 'Mua quà tổng kết năm học & lễ hội mừng ngày Quốc tế Thiếu nhi 1/6',
  },
];

