import { FoodIngredient, FoodIngredientCategory, SchoolInfo } from '@/types/preschool';

export interface StandardIngredientOption {
  name: string;
  category: FoodIngredientCategory;
  type: 'tuoi_song' | 'kho';
  unit: string;
  defaultRawGrams: number;
  defaultCleanGrams: number;
  wasteRatePercent: number;
  defaultPricePerKg: number;
  caloriesPer100g: number;
  proteinPer100g: number;
  lipidPer100g: number;
  glucidPer100g: number;
}

/**
 * Danh mục nguyên liệu chuẩn mầm non - Rút gọn, gãy gọn, không đính kèm thương hiệu dài dòng.
 */
export const STANDARD_INGREDIENT_OPTIONS: StandardIngredientOption[] = [
  // --- GIA VỊ & ĐỒ KHÔ ---
  {
    name: 'Đường kính',
    category: 'Gia vị & dầu mỡ',
    type: 'kho',
    unit: 'kg',
    defaultRawGrams: 3,
    defaultCleanGrams: 3,
    wasteRatePercent: 0,
    defaultPricePerKg: 26000,
    caloriesPer100g: 387,
    proteinPer100g: 0,
    lipidPer100g: 0,
    glucidPer100g: 99.8,
  },
  {
    name: 'Dầu ăn',
    category: 'Gia vị & dầu mỡ',
    type: 'kho',
    unit: 'lít',
    defaultRawGrams: 4,
    defaultCleanGrams: 4,
    wasteRatePercent: 0,
    defaultPricePerKg: 52000,
    caloriesPer100g: 884,
    proteinPer100g: 0,
    lipidPer100g: 100,
    glucidPer100g: 0,
  },
  {
    name: 'Nước mắm',
    category: 'Gia vị & dầu mỡ',
    type: 'kho',
    unit: 'lít',
    defaultRawGrams: 2,
    defaultCleanGrams: 2,
    wasteRatePercent: 0,
    defaultPricePerKg: 42000,
    caloriesPer100g: 35,
    proteinPer100g: 8,
    lipidPer100g: 0,
    glucidPer100g: 1,
  },
  {
    name: 'Muối tinh',
    category: 'Gia vị & dầu mỡ',
    type: 'kho',
    unit: 'kg',
    defaultRawGrams: 1,
    defaultCleanGrams: 1,
    wasteRatePercent: 0,
    defaultPricePerKg: 10000,
    caloriesPer100g: 0,
    proteinPer100g: 0,
    lipidPer100g: 0,
    glucidPer100g: 0,
  },
  {
    name: 'Hạt nêm',
    category: 'Gia vị & dầu mỡ',
    type: 'kho',
    unit: 'kg',
    defaultRawGrams: 1.5,
    defaultCleanGrams: 1.5,
    wasteRatePercent: 0,
    defaultPricePerKg: 65000,
    caloriesPer100g: 120,
    proteinPer100g: 5,
    lipidPer100g: 1,
    glucidPer100g: 22,
  },
  {
    name: 'Bột năng',
    category: 'Gạo & ngũ cốc',
    type: 'kho',
    unit: 'kg',
    defaultRawGrams: 5,
    defaultCleanGrams: 5,
    wasteRatePercent: 0,
    defaultPricePerKg: 32000,
    caloriesPer100g: 342,
    proteinPer100g: 0.1,
    lipidPer100g: 0.1,
    glucidPer100g: 85,
  },
  {
    name: 'Bột sắn dây',
    category: 'Gạo & ngũ cốc',
    type: 'kho',
    unit: 'kg',
    defaultRawGrams: 10,
    defaultCleanGrams: 10,
    wasteRatePercent: 0,
    defaultPricePerKg: 120000,
    caloriesPer100g: 340,
    proteinPer100g: 0.7,
    lipidPer100g: 0.2,
    glucidPer100g: 84.3,
  },
  {
    name: 'Gạo tẻ',
    category: 'Gạo & ngũ cốc',
    type: 'kho',
    unit: 'kg',
    defaultRawGrams: 60,
    defaultCleanGrams: 60,
    wasteRatePercent: 0,
    defaultPricePerKg: 24000,
    caloriesPer100g: 344,
    proteinPer100g: 7.5,
    lipidPer100g: 1,
    glucidPer100g: 76,
  },
  {
    name: 'Gạo nếp',
    category: 'Gạo & ngũ cốc',
    type: 'kho',
    unit: 'kg',
    defaultRawGrams: 50,
    defaultCleanGrams: 50,
    wasteRatePercent: 0,
    defaultPricePerKg: 28000,
    caloriesPer100g: 344,
    proteinPer100g: 8.2,
    lipidPer100g: 1.5,
    glucidPer100g: 74,
  },
  {
    name: 'Đậu xanh',
    category: 'Gạo & ngũ cốc',
    type: 'kho',
    unit: 'kg',
    defaultRawGrams: 15,
    defaultCleanGrams: 15,
    wasteRatePercent: 0,
    defaultPricePerKg: 45000,
    caloriesPer100g: 328,
    proteinPer100g: 23,
    lipidPer100g: 1.2,
    glucidPer100g: 53,
  },
  {
    name: 'Hạt sen',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 15,
    defaultCleanGrams: 13.5,
    wasteRatePercent: 10,
    defaultPricePerKg: 85000,
    caloriesPer100g: 104,
    proteinPer100g: 4.0,
    lipidPer100g: 0.3,
    glucidPer100g: 21,
  },
  {
    name: 'Nui chữ',
    category: 'Gạo & ngũ cốc',
    type: 'kho',
    unit: 'kg',
    defaultRawGrams: 30,
    defaultCleanGrams: 30,
    wasteRatePercent: 0,
    defaultPricePerKg: 38000,
    caloriesPer100g: 360,
    proteinPer100g: 12,
    lipidPer100g: 1.5,
    glucidPer100g: 75,
  },
  {
    name: 'Bánh phở',
    category: 'Gạo & ngũ cốc',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 90,
    defaultCleanGrams: 90,
    wasteRatePercent: 0,
    defaultPricePerKg: 25000,
    caloriesPer100g: 139,
    proteinPer100g: 2.2,
    lipidPer100g: 0.3,
    glucidPer100g: 32,
  },
  {
    name: 'Sữa tươi',
    category: 'Sữa & chế phẩm',
    type: 'kho',
    unit: 'lít',
    defaultRawGrams: 100,
    defaultCleanGrams: 100,
    wasteRatePercent: 0,
    defaultPricePerKg: 38000,
    caloriesPer100g: 64,
    proteinPer100g: 3.2,
    lipidPer100g: 3.5,
    glucidPer100g: 4.8,
  },
  {
    name: 'Sữa chua',
    category: 'Sữa & chế phẩm',
    type: 'kho',
    unit: 'hộp',
    defaultRawGrams: 100,
    defaultCleanGrams: 100,
    wasteRatePercent: 0,
    defaultPricePerKg: 45000,
    caloriesPer100g: 88,
    proteinPer100g: 3.3,
    lipidPer100g: 3.0,
    glucidPer100g: 12,
  },
  {
    name: 'Sữa đặc',
    category: 'Sữa & chế phẩm',
    type: 'kho',
    unit: 'hộp',
    defaultRawGrams: 15,
    defaultCleanGrams: 15,
    wasteRatePercent: 0,
    defaultPricePerKg: 70000,
    caloriesPer100g: 329,
    proteinPer100g: 8.1,
    lipidPer100g: 8.8,
    glucidPer100g: 54.4,
  },

  // --- THỊT, CÁ, HẢI SẢN (TƯƠI SỐNG) ---
  {
    name: 'Thịt lợn nạc',
    category: 'Thịt cá tươi sống',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 50,
    defaultCleanGrams: 42.5,
    wasteRatePercent: 15,
    defaultPricePerKg: 135000,
    caloriesPer100g: 139,
    proteinPer100g: 19,
    lipidPer100g: 7,
    glucidPer100g: 0,
  },
  {
    name: 'Thịt bò',
    category: 'Thịt cá tươi sống',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 45,
    defaultCleanGrams: 31.5,
    wasteRatePercent: 30,
    defaultPricePerKg: 260000,
    caloriesPer100g: 182,
    proteinPer100g: 21.5,
    lipidPer100g: 10.7,
    glucidPer100g: 0,
  },
  {
    name: 'Thịt gà ta',
    category: 'Thịt cá tươi sống',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 40,
    defaultCleanGrams: 32,
    wasteRatePercent: 20,
    defaultPricePerKg: 95000,
    caloriesPer100g: 199,
    proteinPer100g: 20.3,
    lipidPer100g: 13.1,
    glucidPer100g: 0,
  },
  {
    name: 'Tôm tươi',
    category: 'Thủy hải sản',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 50,
    defaultCleanGrams: 25,
    wasteRatePercent: 50,
    defaultPricePerKg: 220000,
    caloriesPer100g: 90,
    proteinPer100g: 18.4,
    lipidPer100g: 1.8,
    glucidPer100g: 0,
  },
  {
    name: 'Cá basa',
    category: 'Thủy hải sản',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 55,
    defaultCleanGrams: 33,
    wasteRatePercent: 40,
    defaultPricePerKg: 90000,
    caloriesPer100g: 124,
    proteinPer100g: 16.5,
    lipidPer100g: 6.5,
    glucidPer100g: 0,
  },
  {
    name: 'Cá thu',
    category: 'Thủy hải sản',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 40,
    defaultCleanGrams: 28,
    wasteRatePercent: 30,
    defaultPricePerKg: 180000,
    caloriesPer100g: 166,
    proteinPer100g: 18.2,
    lipidPer100g: 10.3,
    glucidPer100g: 0,
  },
  {
    name: 'Chả cá',
    category: 'Thủy hải sản',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 40,
    defaultCleanGrams: 38,
    wasteRatePercent: 5,
    defaultPricePerKg: 190000,
    caloriesPer100g: 170,
    proteinPer100g: 15.4,
    lipidPer100g: 6.6,
    glucidPer100g: 2.4,
  },
  {
    name: 'Cua đồng',
    category: 'Thủy hải sản',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 40,
    defaultCleanGrams: 20,
    wasteRatePercent: 50,
    defaultPricePerKg: 110000,
    caloriesPer100g: 87,
    proteinPer100g: 12.3,
    lipidPer100g: 3.3,
    glucidPer100g: 2,
  },
  {
    name: 'Trứng gà',
    category: 'Thịt cá tươi sống',
    type: 'tuoi_song',
    unit: 'quả',
    defaultRawGrams: 25,
    defaultCleanGrams: 22.5,
    wasteRatePercent: 10,
    defaultPricePerKg: 55000,
    caloriesPer100g: 149,
    proteinPer100g: 11.6,
    lipidPer100g: 10.9,
    glucidPer100g: 1,
  },
  {
    name: 'Trứng cút',
    category: 'Thịt cá tươi sống',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 40,
    defaultCleanGrams: 34,
    wasteRatePercent: 15,
    defaultPricePerKg: 65000,
    caloriesPer100g: 154,
    proteinPer100g: 13,
    lipidPer100g: 11,
    glucidPer100g: 1,
  },
  {
    name: 'Đậu phụ',
    category: 'Thịt cá tươi sống',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 40,
    defaultCleanGrams: 40,
    wasteRatePercent: 0,
    defaultPricePerKg: 25000,
    caloriesPer100g: 95,
    proteinPer100g: 10.9,
    lipidPer100g: 5.4,
    glucidPer100g: 0.7,
  },

  // --- RAU CỦ QUẢ NẤM (TƯƠI SỐNG) ---
  {
    name: 'Rau mồng tơi',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 35,
    defaultCleanGrams: 29.75,
    wasteRatePercent: 15,
    defaultPricePerKg: 22000,
    caloriesPer100g: 14,
    proteinPer100g: 2.0,
    lipidPer100g: 0.2,
    glucidPer100g: 2.4,
  },
  {
    name: 'Rau ngót',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 35,
    defaultCleanGrams: 28,
    wasteRatePercent: 20,
    defaultPricePerKg: 28000,
    caloriesPer100g: 35,
    proteinPer100g: 5.3,
    lipidPer100g: 0.4,
    glucidPer100g: 3.4,
  },
  {
    name: 'Rau cải ngọt',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 40,
    defaultCleanGrams: 32,
    wasteRatePercent: 20,
    defaultPricePerKg: 20000,
    caloriesPer100g: 16,
    proteinPer100g: 1.7,
    lipidPer100g: 0.2,
    glucidPer100g: 1.9,
  },
  {
    name: 'Bí đỏ',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 35,
    defaultCleanGrams: 28,
    wasteRatePercent: 20,
    defaultPricePerKg: 20000,
    caloriesPer100g: 27,
    proteinPer100g: 0.9,
    lipidPer100g: 0.1,
    glucidPer100g: 6.1,
  },
  {
    name: 'Bí xanh',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 40,
    defaultCleanGrams: 34,
    wasteRatePercent: 15,
    defaultPricePerKg: 18000,
    caloriesPer100g: 12,
    proteinPer100g: 0.6,
    lipidPer100g: 0.1,
    glucidPer100g: 2.4,
  },
  {
    name: 'Mướp hương',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 25,
    defaultCleanGrams: 20,
    wasteRatePercent: 20,
    defaultPricePerKg: 22000,
    caloriesPer100g: 16,
    proteinPer100g: 0.9,
    lipidPer100g: 0.1,
    glucidPer100g: 3.0,
  },
  {
    name: 'Cà rốt',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 25,
    defaultCleanGrams: 20,
    wasteRatePercent: 20,
    defaultPricePerKg: 22000,
    caloriesPer100g: 39,
    proteinPer100g: 1.5,
    lipidPer100g: 0.2,
    glucidPer100g: 7.8,
  },
  {
    name: 'Khoai tây',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 30,
    defaultCleanGrams: 25.5,
    wasteRatePercent: 15,
    defaultPricePerKg: 25000,
    caloriesPer100g: 77,
    proteinPer100g: 2.0,
    lipidPer100g: 0.1,
    glucidPer100g: 17,
  },
  {
    name: 'Cà chua',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 25,
    defaultCleanGrams: 20,
    wasteRatePercent: 20,
    defaultPricePerKg: 25000,
    caloriesPer100g: 19,
    proteinPer100g: 0.6,
    lipidPer100g: 0.2,
    glucidPer100g: 4.2,
  },
  {
    name: 'Nấm hương',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 10,
    defaultCleanGrams: 8,
    wasteRatePercent: 20,
    defaultPricePerKg: 85000,
    caloriesPer100g: 48,
    proteinPer100g: 2.4,
    lipidPer100g: 0.4,
    glucidPer100g: 8.0,
  },
  {
    name: 'Hành hoa',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 3,
    defaultCleanGrams: 2.85,
    wasteRatePercent: 5,
    defaultPricePerKg: 30000,
    caloriesPer100g: 32,
    proteinPer100g: 1.8,
    lipidPer100g: 0.5,
    glucidPer100g: 5.5,
  },
  {
    name: 'Hành tím',
    category: 'Rau củ quả nấm',
    type: 'tuoi_song',
    unit: 'kg',
    defaultRawGrams: 2,
    defaultCleanGrams: 1.9,
    wasteRatePercent: 5,
    defaultPricePerKg: 45000,
    caloriesPer100g: 45,
    proteinPer100g: 1.2,
    lipidPer100g: 0.1,
    glucidPer100g: 10,
  },
];

/**
 * Trích xuất danh sách Nhà cung cấp & Cơ sở sản xuất có sẵn từ cấu hình trường học
 */
export function getAvailableSuppliers(schoolInfo?: SchoolInfo): { label: string; name: string; type: 'meat' | 'veg' | 'seafood' | 'dry' | 'custom' }[] {
  const result: { label: string; name: string; type: 'meat' | 'veg' | 'seafood' | 'dry' | 'custom' }[] = [];

  if (schoolInfo) {
    if (schoolInfo.meatSupplierName?.trim()) {
      result.push({
        label: `NCC Thịt: ${schoolInfo.meatSupplierName}`,
        name: schoolInfo.meatSupplierName.trim(),
        type: 'meat',
      });
    }
    if (schoolInfo.vegSupplierName?.trim()) {
      result.push({
        label: `NCC Rau củ: ${schoolInfo.vegSupplierName}`,
        name: schoolInfo.vegSupplierName.trim(),
        type: 'veg',
      });
    }
    if (schoolInfo.seafoodSupplierName?.trim()) {
      result.push({
        label: `NCC Thủy hải sản: ${schoolInfo.seafoodSupplierName}`,
        name: schoolInfo.seafoodSupplierName.trim(),
        type: 'seafood',
      });
    }
    if (schoolInfo.drySupplierName?.trim()) {
      result.push({
        label: `NCC Đồ khô & Gia vị: ${schoolInfo.drySupplierName}`,
        name: schoolInfo.drySupplierName.trim(),
        type: 'dry',
      });
    }
    if (schoolInfo.dryProducerName?.trim() && schoolInfo.dryProducerName !== schoolInfo.drySupplierName) {
      result.push({
        label: `Cơ sở sản xuất: ${schoolInfo.dryProducerName}`,
        name: schoolInfo.dryProducerName.trim(),
        type: 'dry',
      });
    }
  }

  // Luôn bổ sung các đối tác chuẩn hóa cơ bản làm phương án dự phòng
  const defaultPartners = [
    { label: 'Cơ sở chuẩn hóa ATTP trường', name: 'Cơ sở chuẩn hóa ATTP trường', type: 'custom' as const },
    { label: 'Đại lý Thực phẩm Sạch', name: 'Đại lý Thực phẩm Sạch', type: 'meat' as const },
    { label: 'Vựa Rau củ Quả An Toàn', name: 'Vựa Rau củ Quả An Toàn', type: 'veg' as const },
    { label: 'Đại lý Bách Hóa Tổng Hợp', name: 'Đại lý Bách Hóa Tổng Hợp', type: 'dry' as const },
  ];

  for (const p of defaultPartners) {
    if (!result.some((r) => r.name.toLowerCase() === p.name.toLowerCase())) {
      result.push(p);
    }
  }

  return result;
}

/**
 * Tự động tìm thông tin chuẩn cho 1 nguyên liệu theo tên
 */
export function findStandardOption(name: string): StandardIngredientOption | undefined {
  const cleanName = (name || '').trim().toLowerCase();
  return STANDARD_INGREDIENT_OPTIONS.find((opt) => {
    const optName = opt.name.toLowerCase();
    return cleanName === optName || cleanName.includes(optName) || optName.includes(cleanName);
  });
}
